config/routes.rb
Nbnstalk::Application.routes.draw do
  get "static_pages/home"
  root to: 'static_pages#home'
  resources :sightings, :only => [:show, :index, :create, :new]
  resources :sessions
  match '/new',    to: 'sightings#new'

  resources :types

end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
	belongs_to :type
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :sightings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
      username == "admin" && password == "test"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  # GET /sightings
  # GET /sightings.json


   
  
  def index
    @sightings = Sighting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sightings }
    end
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
    @sighting = Sighting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sighting }
    end
  end

  # GET /sightings/new
  # GET /sightings/new.json
  def new
    @sighting = Sighting.new
	@types = Type.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sighting }
    end
  end

  # GET /sightings/1/edit
  def edit
	@types = Type.all
    @sighting = Sighting.find(params[:id])
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(params[:sighting])

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to "/static_pages/home", notice: 'Sighting was successfully created.' }
        format.json { render json: @sighting, status: :created, location: @sighting }
      else
        format.html { render action: "new" }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sightings/1
  # PUT /sightings/1.json
  def update
    @sighting = Sighting.find(params[:id])

    respond_to do |format|
      if @sighting.update_attributes(params[:sighting])
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting = Sighting.find(params[:id])
    @sighting.destroy

    respond_to do |format|
      format.html { redirect_to sightings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.json
   before_filter :authenticate, :only => [:new, :destroy, :edit]
  

  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
	
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nbnstalk</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>
		body
{
background: url('/seamlesstexture13_500.jpg');
}
</style>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCLmJSiDdnKyOICJ5RWUtiqDQFiEc31tGA&sensor=false">
    </script>
	</head>
<body onload="initialize()" onunload="GUnload()">

 <div class="container">
	
<%= yield %>
	
	</div>

</body>
</html>

app/views/sightings/_form.html.erb
<br />
<%= form_for(@sighting, :html => { :class => "form-horizontal"} ) do |f| %>
  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% @sighting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :address, :class => 'control-label'  %>
	<div class = "controls">
    <%= f.text_field :address %>
	</div>
  </div>
  <div class="control-group">
    <%= f.label :type_id, :class => 'control-label' %>
	<div class = "controls">
	<%= collection_select(:sighting, :type_id, @types, :id, :name, {:prompt => false })  %>
	</div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label'%>
	<div class = "controls">
    <%= f.text_area :description %>
	 <div class="actions"><br />
    <%= f.submit 'Create Sighting', :class => 'btn btn-primary btn-large' %>
  </div>
	</div>
  </div>
 
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing sighting</h1>

<%= render 'form' %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<h1>Listing sightings</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Lat</th>
    <th>Long</th>
    <th>Type</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sightings.each do |sighting| %>
  <tr>
    <td><%= sighting.address %></td>
    <td><%= sighting.lat %></td>
    <td><%= sighting.long %></td>
    <td><%= sighting.type_id %></td>
    <td><%= sighting.description %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sighting', new_sighting_path %>
<div id="map_canvas" style="width: 500px; height: 300px"></div>

app/views/sightings/new.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="brand"> NBN Stalker</div>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><%= link_to 'Map', "/" %></li>
              <li class="active"><%= link_to 'New Sighting', new_sighting_path %></li>
			  </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class = "hero-unit">
<h1>New sighting</h1>

<%= render 'form' %>

<%= link_to 'Map', "/"%>
</div>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @sighting.address %>
</p>

<p>
  <b>Lat:</b>
  <%= @sighting.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @sighting.long %>
</p>

<p>
  <b>Type:</b>
  <%= @sighting.type_id %>
</p>

<p>
  <b>Description:</b>
  <%= @sighting.description %>
</p>


<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>

app/views/static_pages/home.html.erb
<script type="text/javascript">
function initialize() {
    var mapOptions = {
        center: new google.maps.LatLng(-34.397, 150.644),
        zoom: 8,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map_canvas"),
        mapOptions);
    $.ajaxSetup( {
        "async": false
    } );
    $.getJSON('/sightings.json', function(data) {
        for (var i = 0; i < data.length; i++) {
            addressString = data[i].address
            descriptionString = data[i].description;
			var typeString;
			$.getJSON('/types/' + data[i].type_id, function(type) {
				typeString = type.name;
			});
			var geocoder= new google.maps.Geocoder();
            geocoder.geocode({
                'address' : addressString
            }, function(results, status){
                if (status == google.maps.GeocoderStatus.OK) {
                    var point = new google.maps.LatLng(parseFloat(results[0].geometry.location.lat()), 
                        parseFloat(results[0].geometry.location.lng()));
                    marker = new google.maps.Marker({
                        map:map,
                        html: "<b> Type: </b> " + typeString + "<br />" + 
						"<b> Description: </b> <p>" + descriptionString + "</p>",
                        position: point
                    });
                    var infowindow = new google.maps.InfoWindow({
                        content: "herro"
                    });
                    google.maps.event.addListener(marker, 'click', function() {
                        infowindow.setContent(this.html);
                        infowindow.open(map, this);
                    });
                }
            });
				
        }
    });
	
	
}
    </script>
 <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="brand"> NBN Stalker</div>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to 'Map', "/" %></li>
              <li><%= link_to 'New Sighting', new_sighting_path %></li>
			  </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
 <div class="container">
	<div class = "hero-unit">
	
<h1>Welcome To NBN Stalker</h1>
<p>The National broadband network is one of the most important infrastructure projects for the future of Australia.
Ignore the FUD, a FTTH based NBN is the only sensible way to move forward with broadband policy in australia.</p>
<p>However one area where the NBN has been a let down is updates on progress. There is a "rollout map" but for a lot of people pink and blue splotches dont cut it! 
The solution to this, like most problems, is stalking. </p>
<p>Telecoms forums such as Whirlpool already have groups of people posting about where they have seen NBN progress, this site is meant to be a low overheads way to aggregate that information. 
Its pretty basic, click "New Sighting" up the top, input an approximate address and a the type of sighting (will add to these as they are needed) and put links to relevant pictures (imgur is your friend) in the description.</p>
<p>NBN stalker is built with Ruby on Rails and Twitter Bootstrap</p>

</div>
<div id="map_canvas" style="width: 940px; height: 600px"></div>
</div> <!-- /container -->

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.number_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= type.name %></td>
    <td><%= type.color %></td>
    <td><%= link_to 'Show', type %></td>
    <td><%= link_to 'Edit', edit_type_path(type) %></td>
    <td><%= link_to 'Destroy', type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<p>
  <b>Color:</b>
  <%= @type.color %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>